services:
  - type: web
    name: trustx-server
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTO_START
        value: "true"
      - key: FACILITATOR_URL
        value: https://facilitator.goplausible.xyz
      - key: X402_NETWORK
        value: algorand:SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=
      - key: USDC_ASSET_ID
        value: "10458941"
      - key: PAYMENT_RECEIVER_ADDRESS
        value: N6Y4IYI4GTZJQLJNUSJS2UXWWTUQMKOMHQK3ZPUS5KGPREVZ5HJPCOQ5WA
      - key: PAYMENT_PAYER_ADDRESS
        value: N7RD4M5KFNDANIF4NICNW5SEFQBYMB2URW7GEGBQR5AVNCEOJ6WST3L4LY
      - key: AVM_MNEMONIC
        sync: false
